In [1]:
from time import time
import numpy as np, numpy.random as npr, multiprocessing as mp

In [20]:
def f(x): 
    for i in range(10**8) : pass 
    return np.asarray([x,x*x]) 
   
inputs = npr.randn(20)
start = time()
if __name__ == '__main__': 
    pool = mp.Pool() 
    pool = mp.Pool(processes=5)     
    outputs1 = pool.map(f, inputs) 
time1 = time()-start
print(time1)

5.191797494888306


In [21]:
outputs1

[array([0.13316809, 0.01773374]),
 array([1.2201593 , 1.48878872]),
 array([-1.87041482,  3.49845161]),
 array([-1.61640944,  2.61277949]),
 array([-0.185484  ,  0.03440431]),
 array([-0.18956856,  0.03593624]),
 array([1.59197616, 2.53438809]),
 array([-0.11861775,  0.01407017]),
 array([-2.18825925,  4.78847857]),
 array([2.54198853, 6.46170568]),
 array([0.65811648, 0.4331173 ]),
 array([-1.63007906,  2.65715773]),
 array([0.93876075, 0.88127175]),
 array([2.55160223, 6.51067395]),
 array([-0.61372554,  0.37665903]),
 array([-0.10800094,  0.0116642 ]),
 array([0.39417883, 0.15537695]),
 array([-0.5580115 ,  0.31137684]),
 array([-0.50389108,  0.25390622]),
 array([-2.06685632,  4.27189506])]

In [22]:
start = time()
outputs2 = np.zeros((len(inputs),2))
for (i,x) in enumerate(inputs) :
    outputs2[i] = f(x)
time2 = time()-start
print(time2)

23.81115460395813


In [23]:
time2/time1

4.586302649015472

In [25]:
outputs2

array([[ 0.13316809,  0.01773374],
       [ 1.2201593 ,  1.48878872],
       [-1.87041482,  3.49845161],
       [-1.61640944,  2.61277949],
       [-0.185484  ,  0.03440431],
       [-0.18956856,  0.03593624],
       [ 1.59197616,  2.53438809],
       [-0.11861775,  0.01407017],
       [-2.18825925,  4.78847857],
       [ 2.54198853,  6.46170568],
       [ 0.65811648,  0.4331173 ],
       [-1.63007906,  2.65715773],
       [ 0.93876075,  0.88127175],
       [ 2.55160223,  6.51067395],
       [-0.61372554,  0.37665903],
       [-0.10800094,  0.0116642 ],
       [ 0.39417883,  0.15537695],
       [-0.5580115 ,  0.31137684],
       [-0.50389108,  0.25390622],
       [-2.06685632,  4.27189506]])

In [27]:
outputs1-outputs2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])